# Setup
title: Gruv Poole
tagline: Aesthetic Excellence
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/

sass:
  sass_dir: _sass
  sourcemap: development
  style: compressed

# Specify the author for blog posts
author:
  name: Jamison Griffith
  url: https://jamogriff.dev
  email: jamison.griffith@gmail.com

# Custom vars
version: 0.9.0
