title: Gruv Poole
tagline: Gruvbox Jekyll theme

# Populate about section of homepage
# Name and description are required,
# whereas image and socials are optional
about:
  name: Jamison Griffith
  # The `>` after `description:` means to ignore line-breaks until next key.
  # If you want to omit the line-break after the end of text, use `>-` instead.
  description: >
    Write an awesome description for your new site here. You can edit this line
    in _config.yml. It will appear in your document head meta (for Google search
    results) and in your feed.xml site description.
  image: demo-assets/jamison.jpeg
  # You can add more links here, but icons are only available
  # for these platforms specifically
  socials:
    - { id: github, url: https://github.com/jamogriff }
    - { id: linkedin, url: https://github.com/jamogriff }
    - { id: facebook, url: https://github.com/jamogriff }
    - { id: instagram, url: https://github.com/jamogriff }
    - { id: x, url: https://github.com/jamogriff }

### Developer-oriented config
permalink: pretty
plugins:
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/

liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

sass:
  sass_dir: _sass
  sourcemap: development
  style: compressed
