title: Gruv Poole
tagline: Gruvbox Jekyll theme
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in the about section of the homepage.

# Populate about section of homepage
# These are optional, but the theme
# supports rendering them
about:
  image:
    src: demo-assets/jamo.jpg
    alt: Image of Jamogriff
  # You can add more links here, but icons are only available
  # for these platforms specifically
  socials:
    - { id: github, url: https://github.com/jamogriff }
    - { id: youtube, url: https://github.com/jamogriff }
    - { id: linkedin, url: https://github.com/jamogriff }
    - { id: facebook, url: https://github.com/jamogriff }
    - { id: instagram, url: https://github.com/jamogriff }
    - { id: reddit, url: https://github.com/jamogriff }
    - { id: tiktok, url: https://github.com/jamogriff }
    - { id: x, url: https://github.com/jamogriff }

# Add any pages that you want to be
# included in the masthead's navbar
masthead_pages:
  - about.md

# Replace with your own ID
# if you want Google Analytics
# google_analytics:UA-NNNNNNNN-N

# If you have an RSS
# feed plugin and want to
# advertise the feed, then
# set the feed file here
# rss_feed: atom.xml

# If you intend to use 
# an SEO plugin, then uncomment
# disable_simple_seo: true

### Developer-oriented config
permalink: pretty

# Optimize Jekyll
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/

liquid:
  error_mode: strict
  # Don't really recommend strict mode
  # until this is resolved: https://github.com/Shopify/liquid/issues/1034
  strict_variables: false
  strict_filters: true

sass:
  sass_dir: _sass
  sourcemap: development
  style: compressed
